-- indexes:
DROP INDEX PERSON_LOGIN_IDX;

DROP INDEX GENRE_NAME_IDX;

DROP INDEX EPISODE_LINK_IDX;

DROP INDEX ADS_LINK_IDX;

DROP INDEX LISTENS_TO_DURATION_IDX;

-- constraints
ALTER TABLE S24_S003_T7_LISTENS_TO DROP CONSTRAINT EPISODE_DURATION_CONSTRAINT;

-- triggers
DROP TRIGGER check_podcast_format;

-- tables:
DROP TABLE S24_S003_T7_DISPLAYS PURGE;

DROP TABLE S24_S003_T7_SUBSCRIBES_TO PURGE;

DROP TABLE S24_S003_T7_LISTENS_TO PURGE;

DROP TABLE S24_S003_T7_ADS PURGE;

DROP TABLE S24_S003_T7_EPISODE PURGE;

DROP TABLE S24_S003_T7_PODCAST PURGE;

DROP TABLE S24_S003_T7_ADVERTISER PURGE;

DROP TABLE S24_S003_T7_GENRE PURGE;

DROP TABLE S24_S003_T7_ARTIST PURGE;

DROP TABLE S24_S003_T7_USER PURGE;

DROP TABLE S24_S003_T7_PERSON_PHONE PURGE;

DROP TABLE S24_S003_T7_PERSON PURGE;
